### ISSUE TITLE
Suggestion: Raise minimum reinforcement hardness

### ISSUE THREAD

**Issue by riftcanem** [DevotedMC/Citadel#6]
I lost a few iron ingots by reinforcing a block and then destroying it while /ctb was off. I broke my own reinforcement instead of collecting the reinforcement material. This is reproducible with stone:

1. Reinforce block with stone (only tried /ctf but /ctr probably works the same).
1. Run /cto
1. Break block
1. ???
1. Profit

I suggest setting the minimum reinforcement hardness to 10 breaks or some number greater than 1.

**Comment by TealNerd** [comment]
@ShadedJon this is probably a good idea

**Comment by ShadedJon** [comment]
So this is due to citadel maturation. 

It is working as intended.

If you, or someone else, breaks the block while it is maturing, it will do additional damage to the block.

If you break it instantly without CTB you will lose the reinforcement.

The only way to fix this would be to turn CTB on permanently, if you have access.
